runtime: nodejs18

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

handlers:
  - url: /
    static_files: dist/index.js
    upload: dist/index.js

env_variable:
  DB_USER:
